name = "Daxter Craft Minecraft Modpack 1 . 19 . 2"
author = "Cristian Izzo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92e5c6fd65f8eae67cc90e7b9e297f84c15c3ba02c7d435841259b100a65d560"

[versions]
minecraft = "1.19.2"
quilt = "0.24.0"
