name = "Daxter Craft Minecraft Modpack 1 . 19 . 2"
author = "Cristian Izzo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8de511c39da40271b27cd5dcd0ddf8b638656c3d35b933d790de1096b4cec1cf"

[versions]
minecraft = "1.19.2"
quilt = "0.24.0"
