name = "Daxter Craft Minecraft Modpack 1 . 19 . 2"
author = "Cristian Izzo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "875ce6ad480b40a229a5b6592681a48d811fafbc10ee1c4a0625643982e1aec0"

[versions]
minecraft = "1.19.2"
quilt = "0.24.0"
