name = "Daxter Craft Minecraft Modpack 1 . 19 . 2"
author = "Cristian Izzo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33873df7c3c974b6d58b45c57b4b6cf0dd7d5f89ad7f498dc04876d67e33ff48"

[versions]
minecraft = "1.19.2"
quilt = "0.24.0"
