name = "Daxter Craft Minecraft Modpack 1 . 19 . 2"
author = "Cristian Izzo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50564bafe43b3029e43e2ad8b6b54cef71349d74b91c4d300b0ee2f25c8d179e"

[versions]
minecraft = "1.19.2"
quilt = "0.24.0"
