name = "Daxter Craft Minecraft Modpack 1 . 19 . 2"
author = "Cristian Izzo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f54f450468094df9ae1dd99eb0d9ee85d92609213a02b791ac746c04002f2c3a"

[versions]
minecraft = "1.19.2"
quilt = "0.24.0"
