name = "Daxter Craft Minecraft Modpack 1 . 19 . 2"
author = "Cristian Izzo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6be78398bfaec71773a8ae2d015539e2f9bcb58824afca86652603eadc16d2dd"

[versions]
minecraft = "1.19.2"
quilt = "0.24.0"
