name = "Daxter Craft Minecraft Modpack 1 . 19 . 2"
author = "Cristian Izzo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04fb42762ce1757c5ddc5fa2e4dd80bf4dae28d28c4737a1fe7d998aefcd7a23"

[versions]
minecraft = "1.19.2"
quilt = "0.24.0"
